/* 
    @author	Kamil kamran
    @date	05/08/2024
    @group	EQNUIRY STATUS UPDATE
    @description Apex Object for Parsing Json
    @version 1.0
     */
    // Status Deployed
public class EnquiryRawData{
    public String PrefferredResponseChannel;	
    public String MedicalCenter;	
    public String Queries;	
    public String PhysicianNumber;	
    public String PhysicianEmail;	
    public String Medicine;	
    public String EnquiryName;	
    public String ExternalEnqId;
    public String Physician_Name;
    }